spring.application.name=aula1
spring.datasource.url=jdbc:postgresql://localhost:5432/product-api
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
